                
                                           

       (ns cljx.a
         (:use-macros [clojure.pprint :only [pp]]))

      
(defn p [x]
  (.log js/console x))

     
           
              

(defn both [x]
  (+ x x))

(reify
    cljs.core.IFn    (invoke [_ x] (inc x)))

                                  

(comment foo)

; making sure other tagged literals are left untouched
#whatever [1 2 3]


;;;;;;;;;;;; This file autogenerated from test/cljx/a.cljx
