                
                                           

       (ns cljx.a
         (:use-macros [clojure.pprint :only [pp]]))

      
(defn p [x]
  (.log js/console x))

     
           
              

(defn both [x]
  (+ x x))

(reify
    clojure.lang.IFn (invoke [_ x] (inc x)))

                                  

             


;;;;;;;;;;;; This file autogenerated from test/cljx/a.cljx
