(ns cljx.b
  (                             :require
          [foo.bar]))

     
(defn clj-only [x] "kthx")

      
                                     

             
(defn both [x] "yay")

(defn x
  [y]
  (      +          y y))

;;;;;;;;;;;; This file autogenerated from test/cljx/b.cljx
