(ns cljx.b
  (                       ^:clj :require
          [foo.bar]))

^:clj
(defn clj-only [x] "kthx")

      
                                     

(defn x
  [y]
  (^:clj +          y y))

;;;;;;;;;;;; This file autogenerated from test/cljx/b.cljx
