(ns cljx.b
  (       :require-macros               
          [foo.bar]))

     
                          

      
(defn cljs-only [x] "Internets time")

             
(defn both [x] "yay")

(defn x
  [y]
  (               - y y))

;;;;;;;;;;;; This file autogenerated from test/cljx/b.cljx
