(ns cljx.b
  (^:cljs :require-macros               
          [foo.bar]))

     
                          

^:cljs
(defn cljs-only [x] "Internets time")

(defn x
  [y]
  (        ^:cljs - y y))

;;;;;;;;;;;; This file autogenerated from test/cljx/b.cljx
